[tox]
envlist =
    test-py3{10-13}-qiskit{20-22}
    save-py3{10-13}-qiskit{20-22}
    load-py3{10-13}-qiskit{20-22}
    lint
    coverage
skipsdist = false

[testenv]
install_command = pip install -U {opts:} {packages:}
deps =
    pytest
    pytest-asdf-plugin
    ddt==1.7.2
    qiskit20: qiskit~=2.0
    qiskit21: qiskit~=2.1
    qiskit21: qiskit~=2.2

basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12
    py313: python3.13
    
setenv = 
    py310: PYTHON_VERSION = 3.10
    py311: PYTHON_VERSION = 3.11
    py312: PYTHON_VERSION = 3.12
    py313: PYTHON_VERSION = 3.13
    qiskit20: QISKIT_VERSION = 2.0
    qiskit21: QISKIT_VERSION = 2.1
    qiskit22: QISKIT_VERSION = 2.2

[testenv:save-py3{10-13}-qiskit{20-22}]
description = "Compatibility tests, first stage where data is saved to ASDF files."
commands =
    pytest --quiet -p pytest_asdf_fixtures \
        --asdf-fixtures-save \
        --asdf-fixtures-overwrite \
        --asdf-fixtures-dir=.pytest_asdf_fixtures/py{env:PYTHON_VERSION}_qiskit{env:QISKIT_VERSION} \
        compatibility_tests

[testenv:load-py3{10-13}-qiskit{20-22}]
description = "Compatibility tests, second stage where data is loaded from ASDF files."
commands =
    pytest -p pytest_asdf_fixtures \
    --asdf-fixtures-load \
    ; Qiskit version 2.0.x
    --asdf-fixtures-dir=.pytest_asdf_fixtures/py3.10_qiskit2.0 \
    --asdf-fixtures-dir=.pytest_asdf_fixtures/py3.11_qiskit2.0 \
    --asdf-fixtures-dir=.pytest_asdf_fixtures/py3.12_qiskit2.0 \
    --asdf-fixtures-dir=.pytest_asdf_fixtures/py3.13_qiskit2.0 \
    ; Qiskit version 2.1.x
    --asdf-fixtures-dir=.pytest_asdf_fixtures/py3.10_qiskit2.1 \
    --asdf-fixtures-dir=.pytest_asdf_fixtures/py3.11_qiskit2.1 \
    --asdf-fixtures-dir=.pytest_asdf_fixtures/py3.12_qiskit2.1 \
    --asdf-fixtures-dir=.pytest_asdf_fixtures/py3.13_qiskit2.1 \
    ; Qiskit version 2.2.x
    --asdf-fixtures-dir=.pytest_asdf_fixtures/py3.10_qiskit2.2 \
    --asdf-fixtures-dir=.pytest_asdf_fixtures/py3.11_qiskit2.2 \
    --asdf-fixtures-dir=.pytest_asdf_fixtures/py3.12_qiskit2.2 \
    --asdf-fixtures-dir=.pytest_asdf_fixtures/py3.13_qiskit2.2 \
    compatibility_tests

[testenv:test-py3{10-13}-qiskit{20-22}]
description = "Unit-tests"
commands = 
    pytest tests

[testenv:lint]
description = "Run ruff and license header linting."
deps =
    ruff
commands = 
    ruff check asdf-qiskit
    python ./tools/verify_headers.py

[testenv:coverage]
description = "Compute coverage over all unit-tests with pytest-cov."
deps = 
    pytest
    pytest-cov
    ddt==1.7.2
    -e ./asdf-qiskit
commands = 
    pytest --cov asdf-qiskit --cov-config=.coveragerc
